java:
  VERSION: "java-1.8.0-openjdk"
  ALTERNATIVES: "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.42.amzn1.x86_64/jre/bin/java"

jenkins:
  repo_URL: "http://pkg.jenkins.io/redhat/jenkins.repo"
  gpg_key: "https://pkg.jenkins.io/redhat/jenkins.io.key"
  JAVA_OPTIONS: "-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
